steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--add-cloudsql-instances'
  - '${PROJECT_ID}:${_REGION}:${_SQL_INSTANCE_ID}'
  - '--allow-unauthenticated'
images:
- gcr.io/$PROJECT_ID/wagtail-cloudrun
